package st.indicator.stindicator.presentation.dto;

/** 시그널 판정 근거를 프론트 툴팁과 진단 로그에 전달하는 코드다. */
public enum SignalReasonCode {
    PRICE_ABOVE_VWAP, PRICE_BELOW_VWAP, PRICE_NEAR_VWAP,
    VWAP_SLOPE_UP, VWAP_SLOPE_DOWN, VWAP_SLOPE_FLAT,
    INSUFFICIENT_SESSION_BARS, BULLISH_RECLAIM, BEARISH_REJECTION,
    MACD_ABOVE_SIGNAL, MACD_BELOW_SIGNAL, MACD_ABOVE_ZERO, MACD_BELOW_ZERO,
    HISTOGRAM_POSITIVE, HISTOGRAM_NEGATIVE, HISTOGRAM_TOO_SMALL, MACD_HISTOGRAM_MISMATCH, GOLDEN_CROSS, DEAD_CROSS,
    RSI_ABOVE_MIDDLE, RSI_BELOW_MIDDLE, RSI_IN_NEUTRAL_ZONE,
    RSI_SLOPE_UP, RSI_SLOPE_DOWN, RSI_SLOPE_FLAT, RSI_OVERBOUGHT, RSI_OVERSOLD,
    OVERSOLD_RECOVERY, OVERBOUGHT_REJECTION,
    ADX_BELOW_WEAK_THRESHOLD, ADX_WEAK, ADX_STRONG,
    ADX_RISING, ADX_FALLING, ADX_FLAT,
    PLUS_DI_DOMINANT, MINUS_DI_DOMINANT, DI_SPREAD_TOO_SMALL,
    STRONG_BULLISH_TREND, STRONG_BEARISH_TREND
}
