spring.application.name=stIndicator

spring.datasource.url=${MYSQL_DB_URL}

spring.datasource.username=${MYSQL_DB_USER}
spring.datasource.password=${MYSQL_DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Swagger/OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

#Redis Config
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.timeout=2s

spring.data.redis.lettuce.pool.max-active=8
spring.data.redis.lettuce.pool.max-idle=8
spring.data.redis.lettuce.pool.min-idle=0
spring.data.redis.lettuce.pool.max-wait=1s
#docker run --user root -d --name minio -e "MINIO_ROOT_USER=root" -e "MINIO_ROOT_PASSWORD=1234" -p 4380:9000 -p 4381:9001  -v minio:/data [quay.io/minio/minio](http://quay.io/minio/minio) server /data --console-address ":9001"

#MailService
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.debug=${MAIL_DEBUG_DEV:false}
mail.debug.prod=${MAIL_DEBUG_PROD:false}
front.path=http://localhost:5173/


#JWT
jwt.secret="${JWT_SECRET}
